require: rubocop-performance

AllCops:
  Include:
    - rubocop-rspec
  Exclude:
    - 'spec/**/*'
    - db/schema.rb
  TargetRubyVersion: 2.7.1

Style/Documentation:
  Enabled: false

Layout:
  Metrics/LineLength:
    Max: 140

Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: true

Style/Lambda:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
